### ISSUE TITLE
owl2-swrl not showing subclasses /individuals

### ISSUE THREAD

**Issue by belaazim** [martin-kuba/owl2-swrl-tutorial#1]
Hi,
I tried  to follow your tutorial.
I have a local owl file saved on OWL/XML format (Protege 5).
I have a owl class with different subclasses and individuals.

With the code below no informations has been provided.

OWLClass roleClass = factory.getOWLClass(":Role", pm);
 for (OWLClass role : reasoner.getSubClasses(roleClass, false).getFlattened()) {
            System.out.println("role subclass : " + renderer.render(role));
 }
 for (OWLNamedIndividual roleInd: reasoner.getInstances(roleClass, false).getFlattened()) {
            System.out.println("role individual : " + renderer.render(roleInd));
 }

Any idea please ?

**Comment by martin-kuba** [comment]
This is not an issue with the tutorial. Closing it.
